'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'
import { ThemeProvider as NextThemesProvider } from 'next-themes'

const translations = {
  pt: {
    'brand.title': 'República de Moçambique',
    'brand.subtitle': 'Governo Digital',
    'nav.services': 'Serviços',
    'nav.government': 'Governo',
    'nav.mozambique': 'Moçambique',
    'nav.news': 'Notícias',
    'nav.search': 'Pesquisar',
    'nav.theme.light': 'Modo claro',
    'nav.theme.dark': 'Modo escuro',
    'nav.language': 'Idioma',
    'hero.badge': 'Portal Oficial do Governo',
    'hero.title.line1': 'Construindo um',
    'hero.title.line2': 'Moçambique Digital',
    'hero.subtitle': 'Acesso simples, moderno e transparente aos serviços do Governo de Moçambique.',
    'hero.cta.primary': 'Explorar Serviços',
    'hero.cta.secondary': 'Portal do Cidadão',
    'quick.bi': 'Bilhete de Identidade',
    'quick.passport': 'Passaporte',
    'quick.nuit': 'NUIT',
    'quick.public': 'Serviços Públicos',
    'quick.invest': 'Investir em Moçambique',
    'quick.employee': 'Portal do Funcionário',
    'stats.population': 'População',
    'stats.provinces': 'Províncias',
    'stats.digital': 'Serviços Digitais',
    'stats.satisfaction': 'Satisfação Cidadã',
    'services.badge': 'Serviços Digitais',
    'services.title': 'Serviços ao Seu Alcance',
    'services.subtitle': 'Aceda aos serviços públicos de forma rápida, segura e conveniente',
    'services.search': 'Pesquisar serviços...',
    'services.cta': 'Explorar',
    'services.cat.identification': 'Identificação',
    'services.cat.identification.desc': 'Documentos e registo civil',
    'services.cat.education': 'Educação',
    'services.cat.education.desc': 'Ensino e formação',
    'services.cat.health': 'Saúde',
    'services.cat.health.desc': 'Serviços de saúde pública',
    'services.cat.transport': 'Transportes',
    'services.cat.transport.desc': 'Carta de condução e veículos',
    'services.cat.investment': 'Investimento',
    'services.cat.investment.desc': 'Negócios e investimento',
    'services.cat.taxes': 'Impostos',
    'services.cat.taxes.desc': 'Serviços fiscais',
    'services.cat.justice': 'Justiça',
    'services.cat.justice.desc': 'Serviços jurídicos',
    'services.cat.jobs': 'Emprego',
    'services.cat.jobs.desc': 'Oportunidades de trabalho',
    'services.cat.agriculture': 'Agricultura',
    'services.cat.agriculture.desc': 'Apoio ao sector agrícola',
    'gov.badge': 'Estrutura do Estado',
    'gov.title': 'Governo de Moçambique',
    'gov.subtitle': 'Conheça a estrutura organizacional do governo',
    'gov.presidency': 'Presidência da República',
    'gov.presidency.desc': 'Chefe de Estado e Comandante Supremo',
    'gov.council': 'Conselho de Ministros',
    'gov.council.desc': 'Órgão colegial de governo',
    'gov.visit.portal': 'Visitar Portal',
    'gov.view.composition': 'Ver Composição',
    'gov.visit': 'Visitar',
    'gov.min.finance': 'Ministério das Finanças',
    'gov.min.finance.desc': 'Gestão Económica',
    'gov.min.health': 'Ministério da Saúde',
    'gov.min.health.desc': 'Saúde Pública',
    'gov.min.education': 'Ministério da Educação',
    'gov.min.education.desc': 'Educação e Desenvolvimento Humano',
    'gov.min.interior': 'Ministério do Interior',
    'gov.min.interior.desc': 'Segurança Interna',
    'gov.min.transport': 'Ministério dos Transportes',
    'gov.min.transport.desc': 'Infraestrutura e Mobilidade',
    'gov.min.agriculture': 'Ministério da Agricultura',
    'gov.min.agriculture.desc': 'Agricultura e Desenvolvimento Rural',
    'discover.badge': 'Descubra',
    'discover.title': 'Conheça Moçambique',
    'discover.subtitle': 'Um país diverso, vibrante e em crescimento',
    'discover.economy.title': 'Economia em Crescimento',
    'discover.economy.desc': 'Oportunidades de investimento e desenvolvimento',
    'discover.economy.cta': 'Investir em Moçambique',
    'discover.culture.title': 'Cultura Vibrante',
    'discover.culture.desc': 'Rica diversidade cultural e tradições',
    'discover.culture.cta': 'Explorar Cultura',
    'discover.provinces': '11 Províncias',
    'news.badge': 'Centro de Notícias',
    'news.title': 'Últimas Notícias',
    'news.subtitle': 'Mantenha-se informado sobre as ações do governo',
    'news.all': 'Ver Todas',
    'news.read': 'Ler Mais',
    'news.item1.title': 'Presidente inaugura novo hospital central em Maputo',
    'news.item1.cat': 'Saúde',
    'news.item2.title': 'Nova plataforma digital facilita acesso a serviços públicos',
    'news.item2.cat': 'Tecnologia',
    'news.item3.title': 'Investimento estrangeiro cresce 34% no primeiro trimestre',
    'news.item3.cat': 'Economia',
    'digital.badge': 'Inovação',
    'digital.title': 'Governo Digital',
    'digital.subtitle': 'Transformação digital para um serviço público mais eficiente',
    'digital.online.title': 'Serviços Online',
    'digital.online.desc': '150+ serviços digitais',
    'digital.security.title': 'Segurança Digital',
    'digital.security.desc': 'Proteção de dados',
    'digital.innovation.title': 'Inovação',
    'digital.innovation.desc': 'Tecnologia de ponta',
    'digital.access.title': 'Acessibilidade',
    'digital.access.desc': 'Disponível 24/7',
    'footer.tagline': 'Portal oficial do Governo de Moçambique',
    'footer.services': 'Serviços',
    'footer.government': 'Governo',
    'footer.contact': 'Contacto',
    'footer.s1': 'Bilhete de Identidade',
    'footer.s2': 'Passaporte',
    'footer.s3': 'NUIT',
    'footer.s4': 'Carta de Condução',
    'footer.s5': 'Registo de Empresa',
    'footer.g1': 'Presidência',
    'footer.g2': 'Conselho de Ministros',
    'footer.g3': 'Ministérios',
    'footer.g4': 'Províncias',
    'footer.g5': 'Assembleia da República',
    'footer.rights': '© 2026 Governo de Moçambique. Todos os direitos reservados. | Desenvolvido por Shelton J - All Ventures',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Uso',
    'footer.accessibility': 'Acessibilidade',
  },

  en: {
    'brand.title': 'Republic of Mozambique',
    'brand.subtitle': 'Digital Government',
    'nav.services': 'Services',
    'nav.government': 'Government',
    'nav.mozambique': 'Mozambique',
    'nav.news': 'News',
    'nav.search': 'Search',
    'nav.theme.light': 'Light mode',
    'nav.theme.dark': 'Dark mode',
    'nav.language': 'Language',
    'hero.badge': 'Official Government Portal',
    'hero.title.line1': 'Building a',
    'hero.title.line2': 'Digital Mozambique',
    'hero.subtitle': 'Simple, modern and transparent access to the services of the Government of Mozambique.',
    'hero.cta.primary': 'Explore Services',
    'hero.cta.secondary': 'Citizen Portal',
    'quick.bi': 'ID Card',
    'quick.passport': 'Passport',
    'quick.nuit': 'Tax ID (NUIT)',
    'quick.public': 'Public Services',
    'quick.invest': 'Invest in Mozambique',
    'quick.employee': 'Employee Portal',
    'stats.population': 'Population',
    'stats.provinces': 'Provinces',
    'stats.digital': 'Digital Services',
    'stats.satisfaction': 'Citizen Satisfaction',
    'services.badge': 'Digital Services',
    'services.title': 'Services at Your Fingertips',
    'services.subtitle': 'Access public services quickly, securely and conveniently',
    'services.search': 'Search services...',
    'services.cta': 'Explore',
    'services.cat.identification': 'Identification',
    'services.cat.identification.desc': 'Documents and civil registry',
    'services.cat.education': 'Education',
    'services.cat.education.desc': 'Schooling and training',
    'services.cat.health': 'Health',
    'services.cat.health.desc': 'Public health services',
    'services.cat.transport': 'Transport',
    'services.cat.transport.desc': 'Driving licence and vehicles',
    'services.cat.investment': 'Investment',
    'services.cat.investment.desc': 'Business and investment',
    'services.cat.taxes': 'Taxes',
    'services.cat.taxes.desc': 'Tax services',
    'services.cat.justice': 'Justice',
    'services.cat.justice.desc': 'Legal services',
    'services.cat.jobs': 'Employment',
    'services.cat.jobs.desc': 'Job opportunities',
    'services.cat.agriculture': 'Agriculture',
    'services.cat.agriculture.desc': 'Support for the agricultural sector',
    'gov.badge': 'State Structure',
    'gov.title': 'Government of Mozambique',
    'gov.subtitle': 'Get to know the organisational structure of the government',
    'gov.presidency': 'Presidency of the Republic',
    'gov.presidency.desc': 'Head of State and Supreme Commander',
    'gov.council': 'Council of Ministers',
    'gov.council.desc': 'Collegial body of government',
    'gov.visit.portal': 'Visit Portal',
    'gov.view.composition': 'View Composition',
    'gov.visit': 'Visit',
    'gov.min.finance': 'Ministry of Finance',
    'gov.min.finance.desc': 'Economic Management',
    'gov.min.health': 'Ministry of Health',
    'gov.min.health.desc': 'Public Health',
    'gov.min.education': 'Ministry of Education',
    'gov.min.education.desc': 'Education and Human Development',
    'gov.min.interior': 'Ministry of the Interior',
    'gov.min.interior.desc': 'Internal Security',
    'gov.min.transport': 'Ministry of Transport',
    'gov.min.transport.desc': 'Infrastructure and Mobility',
    'gov.min.agriculture': 'Ministry of Agriculture',
    'gov.min.agriculture.desc': 'Agriculture and Rural Development',
    'discover.badge': 'Discover',
    'discover.title': 'Get to Know Mozambique',
    'discover.subtitle': 'A diverse, vibrant and growing country',
    'discover.economy.title': 'Growing Economy',
    'discover.economy.desc': 'Opportunities for investment and development',
    'discover.economy.cta': 'Invest in Mozambique',
    'discover.culture.title': 'Vibrant Culture',
    'discover.culture.desc': 'Rich cultural diversity and traditions',
    'discover.culture.cta': 'Explore Culture',
    'discover.provinces': '11 Provinces',
    'news.badge': 'News Centre',
    'news.title': 'Latest News',
    'news.subtitle': 'Stay informed about government actions',
    'news.all': 'View All',
    'news.read': 'Read More',
    'news.item1.title': 'President inaugurates new central hospital in Maputo',
    'news.item1.cat': 'Health',
    'news.item2.title': 'New digital platform makes public services more accessible',
    'news.item2.cat': 'Technology',
    'news.item3.title': 'Foreign investment grows 34% in the first quarter',
    'news.item3.cat': 'Economy',
    'digital.badge': 'Innovation',
    'digital.title': 'Digital Government',
    'digital.subtitle': 'Digital transformation for more efficient public services',
    'digital.online.title': 'Online Services',
    'digital.online.desc': '150+ digital services',
    'digital.security.title': 'Digital Security',
    'digital.security.desc': 'Data protection',
    'digital.innovation.title': 'Innovation',
    'digital.innovation.desc': 'Cutting-edge technology',
    'digital.access.title': 'Accessibility',
    'digital.access.desc': 'Available 24/7',
    'footer.tagline': 'Official Portal of the Government of Mozambique',
    'footer.services': 'Services',
    'footer.government': 'Government',
    'footer.contact': 'Contact',
    'footer.s1': 'ID Card',
    'footer.s2': 'Passport',
    'footer.s3': 'Tax ID (NUIT)',
    'footer.s4': 'Driving Licence',
    'footer.s5': 'Business Registration',
    'footer.g1': 'Presidency',
    'footer.g2': 'Council of Ministers',
    'footer.g3': 'Ministries',
    'footer.g4': 'Provinces',
    'footer.g5': 'Assembly of the Republic',
    'footer.rights': '© 2026 Government of Mozambique. All rights reserved. | Developed by Shelton J - All Ventures',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.accessibility': 'Accessibility',
  },

  ts: {
    'brand.title': 'Tiko ra Mozambique',
    'brand.subtitle': 'Mfumo wa Dijithali',
    'nav.services': 'Mintirho',
    'nav.government': 'Mfumo',
    'nav.mozambique': 'Mozambique',
    'nav.news': 'Mahungu',
    'nav.search': 'Lavisisa',
    'nav.theme.light': 'Xivumbeko xo basa',
    'nav.theme.dark': 'Xivumbeko xo nyamalala',
    'nav.language': 'Ririmi',
    'hero.badge': 'Phorthali ya Mfumo',
    'hero.title.line1': 'Hi aka',
    'hero.title.line2': 'Mozambique wa Dijithali',
    'hero.subtitle': 'Ku fikelela ko olova, ko antswisa na ku vonaka ka mintirho ya Mfumo wa Mozambique.',
    'hero.cta.primary': 'Vona Mintirho',
    'hero.cta.secondary': 'Phorthali ya Muaki-tiko',
    'quick.bi': 'Khadi ra Vutivi',
    'quick.passport': 'Phasaphoti',
    'quick.nuit': 'NUIT',
    'quick.public': 'Mintirho ya Vanhu',
    'quick.invest': 'Veka Mali eMozambique',
    'quick.employee': 'Phorthali ya Vatirhi',
    'stats.population': 'Vanhu',
    'stats.provinces': 'Swifundzhankulu',
    'stats.digital': 'Mintirho ya Dijithali',
    'stats.satisfaction': 'Ku Tsakisa Vanhu',
    'services.badge': 'Mintirho ya Dijithali',
    'services.title': 'Mintirho eKusuhi na Wena',
    'services.subtitle': 'Fikelela mintirho ya vanhu hi ku hatlisa, hi ku hlayiseka na hi ku olova',
    'services.search': 'Lavisisa mintirho...',
    'services.cta': 'Vona',
    'services.cat.identification': 'Vutivi',
    'services.cat.identification.desc': 'Mintsalwa na ku tsariwa',
    'services.cat.education': 'Dyondzo',
    'services.cat.education.desc': 'Dyondzo na vuleteri',
    'services.cat.health': 'Rihanyo',
    'services.cat.health.desc': 'Mintirho ya rihanyo ra vanhu',
    'services.cat.transport': 'Vufambisi',
    'services.cat.transport.desc': 'Khadi ra ku chayela na movha',
    'services.cat.investment': 'Mali yo Vekiwa',
    'services.cat.investment.desc': 'Bhindzu na mali yo vekiwa',
    'services.cat.taxes': 'Swibalo',
    'services.cat.taxes.desc': 'Mintirho ya swibalo',
    'services.cat.justice': 'Vululami',
    'services.cat.justice.desc': 'Mintirho ya nawu',
    'services.cat.jobs': 'Ntirho',
    'services.cat.jobs.desc': 'Mikhuva ya ntirho',
    'services.cat.agriculture': 'Vurimi',
    'services.cat.agriculture.desc': 'Ku pfuna vurimi',
    'gov.badge': 'Vuvumbiwi bya Tiko',
    'gov.title': 'Mfumo wa Mozambique',
    'gov.subtitle': 'Tiva vuvumbiwi bya mfumo',
    'gov.presidency': 'Vuphurezidente bya Tiko',
    'gov.presidency.desc': 'Hosi ya Tiko na Mulawuri Lonkulu',
    'gov.council': 'Huvo ya Vatirhisi',
    'gov.council.desc': 'Huvo ya mfumo',
    'gov.visit.portal': 'Endzela Phorthali',
    'gov.view.composition': 'Vona Vatirhisi',
    'gov.visit': 'Endzela',
    'gov.min.finance': 'Wutirhisi bya Timali',
    'gov.min.finance.desc': 'Vufambisi bya Mali',
    'gov.min.health': 'Wutirhisi bya Rihanyo',
    'gov.min.health.desc': 'Rihanyo ra Vanhu',
    'gov.min.education': 'Wutirhisi bya Dyondzo',
    'gov.min.education.desc': 'Dyondzo na Nhluvuko wa Vanhu',
    'gov.min.interior': 'Wutirhisi bya le Ndzeni',
    'gov.min.interior.desc': 'Vuhlayiseki bya ndzeni',
    'gov.min.transport': 'Wutirhisi bya Vufambisi',
    'gov.min.transport.desc': 'Switirhisiwa na Vufambi',
    'gov.min.agriculture': 'Wutirhisi bya Vurimi',
    'gov.min.agriculture.desc': 'Vurimi na Nhluvuko wa Maganga',
    'discover.badge': 'Kuma',
    'discover.title': 'Tiva Mozambique',
    'discover.subtitle': 'Tiko ra mihandzu yo hambana, yo hanya na yo kula',
    'discover.economy.title': 'Ikhonomi yo Kula',
    'discover.economy.desc': 'Mikhuva yo veka mali na yo hluvukisa',
    'discover.economy.cta': 'Veka Mali eMozambique',
    'discover.culture.title': 'Mukhuva wo Hanya',
    'discover.culture.desc': 'Mihandzu yo tala ya ndzhavuko',
    'discover.culture.cta': 'Vona Mukhuva',
    'discover.provinces': 'Swifundzhankulu swa 11',
    'news.badge': 'Senthara ya Mahungu',
    'news.title': 'Mahungu yo Sungula',
    'news.subtitle': 'Tiva swiendlo swa mfumo',
    'news.all': 'Vona Hinkwaswo',
    'news.read': 'Hlaya Swo Tala',
    'news.item1.title': 'Phurezidente u pfula xibedhlele lexintshwa eMaputo',
    'news.item1.cat': 'Rihanyo',
    'news.item2.title': 'Phulathifomu leyintshwa yi olovisa mintirho ya vanhu',
    'news.item2.cat': 'Thekinoloji',
    'news.item3.title': 'Mali yo huma ehandle yi kula hi 34% eka kotara yo sungula',
    'news.item3.cat': 'Ikhonomi',
    'digital.badge': 'Vutivi byintshwa',
    'digital.title': 'Mfumo wa Dijithali',
    'digital.subtitle': 'Ku hundzuka ka dijithali ku endlela mintirho leyi pfunaka swinene',
    'digital.online.title': 'Mintirho ya Onlayini',
    'digital.online.desc': '150+ mintirho ya dijithali',
    'digital.security.title': 'Vuhlayiseki bya Dijithali',
    'digital.security.desc': 'Vuhlayisi bya datha',
    'digital.innovation.title': 'Vutivi byintshwa',
    'digital.innovation.desc': 'Thekinoloji yintshwa',
    'digital.access.title': 'Ku Fikeleleka',
    'digital.access.desc': 'Yi kona masiku hinkwawo',
    'footer.tagline': 'Phorthali ya Mfumo wa Mozambique',
    'footer.services': 'Mintirho',
    'footer.government': 'Mfumo',
    'footer.contact': 'Vuhlanganisi',
    'footer.s1': 'Khadi ra Vutivi',
    'footer.s2': 'Phasaphoti',
    'footer.s3': 'NUIT',
    'footer.s4': 'Khadi ra ku Chayela',
    'footer.s5': 'Ku Tsarisa Bhindzu',
    'footer.g1': 'Vuphurezidente',
    'footer.g2': 'Huvo ya Vatirhisi',
    'footer.g3': 'Tihofisi ta Vutirhisi',
    'footer.g4': 'Swifundzhankulu',
    'footer.g5': 'Hubye ya Tiko',
    'footer.rights': '© 2026 Mfumo wa Mozambique. Timfanelo hinkwato ti hlayisiwile. | Ku endliwa hi Shelton J - All Ventures',
    'footer.privacy': 'Pholisi ya Vuhlayiseki',
    'footer.terms': 'Milawu yo Tirhisa',
    'footer.accessibility': 'Ku Fikeleleka',
  },
}

const LANGUAGES = [
  { code: 'pt', label: 'Português', flag: 'PT' },
  { code: 'en', label: 'English', flag: 'EN' },
  { code: 'ts', label: 'Changana', flag: 'TS' },
]

const LanguageContext = createContext({
  language: 'pt',
  setLanguage: () => {},
  t: (key) => key,
  languages: LANGUAGES,
})

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('pt')

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang)
      try { localStorage.setItem('portal_lang', lang) } catch (e) {}
    }
  }

  const t = (key) => {
    const dict = translations[language] || translations.pt
    return dict[key] ?? translations.pt[key] ?? key
  }

  useEffect(() => {
    try {
      const stored = localStorage.getItem('portal_lang')
      if (stored && translations[stored]) setLanguageState(stored)
    } catch (e) {}
  }, [])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useTranslation() {
  return useContext(LanguageContext)
}

export function ThemeProvider({ children, ...props }) {
  return (
    <NextThemesProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem={false}
      {...props}
    >
      {children}
    </NextThemesProvider>
  )
}


export default function Providers({ children }) {
  return (
    <ThemeProvider>
      <LanguageProvider>{children}</LanguageProvider>
    </ThemeProvider>
  )
}